-- 删除评论表
DROP TABLE IF EXISTS `T_COMMENT` ;
-- 删除消息表
DROP TABLE IF EXISTS `T_MSG`;
-- 删除账户表
DROP TABLE IF EXISTS `T_ACCOUNT`;
-- 删除资料表
DROP TABLE IF EXISTS `T_PROFILE`;
-- 删除用户表
DROP TABLE IF EXISTS `T_USER`;
-- 删除sequence生成器表
DROP TABLE IF EXISTS `T_SEQ_GEN`;
-- 删除配置项表
DROP TABLE IF EXISTS `T_CONFIG`;

COMMIT;

