-- 用户表
CREATE TABLE IF NOT EXISTS `T_USER`
(
	`UID`				INT				NOT NULL COMMENT '用户唯一标识，最大长度10位',
	`CREATE_TIME`		VARCHAR(36)		NOT NULL COMMENT '用户创建时间，格式为yyyyMMddHHmmss的14位UTC时间戳',
	`STATUS`			CHAR(1)			NOT NULL COMMENT '用户状态，1正常; 2封存(用户销户);3锁定;4未激活',
	`PASSWORD`			TEXT(512)		NOT NULL COMMENT '用户密码，经不可逆加密算法加密得到',
	PRIMARY KEY `PK_UID` (`UID`),
	INDEX `IND_STATUS` (`STATUS`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户表';

-- 用户资料表
CREATE TABLE IF NOT EXISTS `T_PROFILE`
(
	`PROFILE_ID`		VARCHAR(64)		NOT NULL COMMENT '用户资料ID, UUID格式, 主键',
	`UID`				INT				NOT NULL COMMENT '用户唯一标识，是T_USER外键',
	`USERNAME`			VARCHAR(128)			COMMENT '用户名',
	`EMAIL`				VARCHAR(128)	NOT NULL COMMENT '邮箱',
	`MOBILE_PHONE`		VARCHAR(32)				COMMENT '手机号码',
	`BRIEF`				TEXT(4096)				COMMENT '个人简介',
	PRIMARY KEY `PK_PROFILE_ID` (`PROFILE_ID`),
	FOREIGN KEY `FK_UID` (`UID`) REFERENCES `T_USER` (`UID`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment '用户资料表';

-- 账号表
CREATE TABLE IF NOT EXISTS `T_ACCOUNT`
(
	`ACCOUNT_ID`		VARCHAR(64)		NOT NULL COMMENT '账号ID, UUID格式, 主键',
	`UID`				INT				NOT NULL COMMENT '用户唯一标识，是T_USER外键',
	`ACCOUNT_NAME`		VARCHAR(128)	NOT NULL COMMENT '账号名, 主键',
	PRIMARY KEY `PK_ACCOUNT_ID` (`ACCOUNT_ID`),
	FOREIGN KEY `FK_UID` (`UID`) REFERENCES `T_USER` (`UID`) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE `UNI_ACC_NAME` (`ACCOUNT_NAME`),
	INDEX `IND_UID` (`UID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment '用户账号表，一个用户可以使用多个账号登录系统';

-- 消息表T_MSG
CREATE TABLE IF NOT EXISTS `T_MSG`
(
	`MSG_ID`			VARCHAR(64)		NOT NULL COMMENT '消息ID, UUID格式, 主键',
	`UID`				INT				NOT NULL COMMENT '消息发布者ID，是T_USER外键',
	`CREATE_TIME`		VARCHAR(36)		NOT NULL COMMENT '消息发布时间，格式为yyyyMMddHHmmss的14位UTC时间戳',
	`UPDATE_TIME`		VARCHAR(36)				COMMENT '消息最近更新时间，格式为yyyyMMddHHmmss的14位UTC时间戳',
	`TEXT`				TEXT(65535)				COMMENT '内容, 文本，最大65535个字符',
	`MULTI_MEDIA`		TEXT(65535)				COMMENT '媒体内容, 可以是图片、视频链接，最大65535个字符',
	PRIMARY KEY `PK_MSG` (`MSG_ID`),
	INDEX `IND_UID` (`UID`),
	FOREIGN KEY `FK_UID` (`UID`) REFERENCES T_USER (`UID`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment '消息表';

-- 消息表T_COMMENT
CREATE TABLE IF NOT EXISTS `T_COMMENT`
(
	`COMMENT_ID`		VARCHAR(64)		NOT NULL COMMENT '评论ID, UUID格式, 主键',
	`MSG_ID`			VARCHAR(64)		NOT NULL COMMENT '评论的消息ID, UUID格式, 外键',
	`UID`				INT				NOT NULL COMMENT '评论者ID，是T_USER外键',
	`CREATE_TIME`		VARCHAR(36)		NOT NULL COMMENT '评论发布时间，格式为yyyyMMddHHmmss的14位UTC时间戳',
	`UPDATE_TIME`		VARCHAR(36)				COMMENT '评论最近更新时间，格式为yyyyMMddHHmmss的14位UTC时间戳',
	`TEXT`				TEXT(65535)				COMMENT '内容, 文本，最大65535个字符',
	`MULTI_MEDIA`		TEXT(65535)				COMMENT '媒体内容, 可以是图片、视频链接，最大65535个字符',
	PRIMARY KEY `PK_COMMENT` (`COMMENT_ID`),
	INDEX `IND_MSG_ID` (`MSG_ID`),
	INDEX `IND_UID` (`UID`),
	FOREIGN KEY `FK_UID` (`UID`) REFERENCES T_USER (`UID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY `FK_MSG_ID` (`MSG_ID`) REFERENCES T_MSG (`MSG_ID`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment '评论表';

-- sequence生成器T_SEQ_GEN
CREATE TABLE IF NOT EXISTS `T_SEQ_GEN`
(
	`SEQ_ID`				VARCHAR(64)		NOT NULL COMMENT 'SEQID',
	`SEQ_VAL`				BIGINT		NOT NULL DEFAULT 0 	COMMENT 'UID序列',
	PRIMARY KEY `PK_SEQ_GEN` (`SEQ_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment 'sequence生成器';

-- 增加UID的sequence生成器
INSERT INTO `T_SEQ_GEN` (`SEQ_ID`,`SEQ_VAL`)
VALUES ('SEQ_UID',0);

-- 配置项表T_CONFIG
CREATE TABLE IF NOT EXISTS `T_CONFIG`
(
	`CONFIG_NAME`		VARCHAR(128)		NOT NULL COMMENT '配置项名称, 主键',
	`CONFIG_VALUE`		TEXT(1024)				COMMENT '配置项值',
	PRIMARY KEY `PK_CONFIG` (`CONFIG_NAME`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 comment '配置项表';

COMMIT;

